import { expect, test } from '@playwright/test'
import { login, expectNoOverflow } from './session-helpers'

test.skip(process.env.E2E_PRODUCTION === 'true', 'PO persistent mock workflow')
const path = '/app/purchase-orders'
test('creates and edits a persisted multi-line PO then submits and locks it', async ({
    page,
}, info) => {
    await login(page, 'user@woodflow.test', path)
    await expect(page.getByText('25 PO', { exact: true })).toBeVisible()
    await page.getByRole('button', { name: 'Berikutnya', exact: true }).click()
    await expect(page).toHaveURL(/page=2/)
    await page.getByRole('link', { name: 'Tambah PO', exact: true }).click()
    await page.getByRole('button', { name: 'Simpan draft', exact: true }).click()
    await expect(page.getByLabel('Buyer', { exact: true })).toBeFocused()
    await page.getByLabel('Buyer', { exact: true }).selectOption('demo-buyer-01')
    await page.getByLabel('Nomor PO', { exact: true }).fill('DEMO-PO-UAT')
    await page.getByLabel('Tanggal PO', { exact: true }).fill('2026-09-26')
    await page.getByLabel('Kayu baris 1', { exact: true }).selectOption('demo-timber-01')
    await page.getByLabel('Jumlah baris 1', { exact: true }).fill('3')
    await page.getByLabel('Harga satuan baris 1', { exact: true }).fill('0.10')
    await page.getByRole('button', { name: 'Tambah baris', exact: true }).click()
    await page.getByLabel('Kayu baris 2', { exact: true }).selectOption('demo-timber-02')
    await page.getByLabel('Harga satuan baris 2', { exact: true }).fill('100.00')
    await page.getByRole('link', { name: 'Batal', exact: true }).click()
    await expect(page.getByRole('dialog', { name: 'Buang perubahan?' })).toBeVisible()
    await page.getByRole('dialog').getByRole('button', { name: 'Batal', exact: true }).click()
    await page.getByRole('button', { name: 'Simpan draft', exact: true }).click()
    await expect(page.getByRole('heading', { name: 'Detail PO', exact: true })).toBeVisible()
    await expect(page.getByText('Rp 100,30', { exact: true })).toBeVisible()
    await page.reload()
    await expect(page.getByText('Kayu Simulasi 02', { exact: true })).toBeVisible()
    await page.getByRole('link', { name: 'Edit PO', exact: true }).click()
    await page.getByLabel('Catatan', { exact: true }).fill('Catatan pengujian sintetis')
    await page.getByRole('button', { name: 'Simpan draft', exact: true }).click()
    await expect(page.getByText('Catatan pengujian sintetis', { exact: true })).toBeVisible()
    await page.getByRole('button', { name: 'Submit PO', exact: true }).click()
    await expect(
        page.getByRole('dialog').getByRole('button', { name: 'Batal', exact: true }),
    ).toBeFocused()
    await page.getByRole('dialog').getByRole('button', { name: 'Konfirmasi', exact: true }).click()
    await expect(page.getByText('Diajukan', { exact: true })).toBeVisible()
    await expect(page.getByRole('link', { name: 'Edit PO', exact: true })).toHaveCount(0)
    await expectNoOverflow(page)
    await page.screenshot({ path: info.outputPath('purchase-order-detail.png'), fullPage: true })
    await page.getByRole('link', { name: 'Kembali ke daftar', exact: true }).click()
    await expect(page).toHaveURL(/page=2/)
})
test('keeps filters in URL and denies foreign records and unpermitted routes', async ({ page }) => {
    await login(page, 'user@woodflow.test', path)
    await page.getByLabel('Status', { exact: true }).selectOption('closed')
    await page.getByRole('button', { name: 'Terapkan filter' }).click()
    await expect(page).toHaveURL(/status=closed/)
    await expect(page.getByText('5 PO', { exact: true })).toBeVisible()
    await page.reload()
    await expect(page.getByLabel('Status', { exact: true })).toHaveValue('closed')
    await page.goto(path + '/demo-po-26')
    await expect(page.getByText('PO tidak ditemukan atau tidak dapat diakses.')).toBeVisible()
    await expect(page.getByText('DEMO-PO-26', { exact: true })).toHaveCount(0)
})
test('supports rejected resubmission and blocks approved editing', async ({ page }) => {
    await login(page, 'user@woodflow.test', path + '/demo-po-04/edit')
    await page.getByLabel('Catatan', { exact: true }).fill('Perbaikan')
    await page.getByRole('button', { name: 'Simpan draft', exact: true }).click()
    await page.getByRole('button', { name: 'Submit PO', exact: true }).click()
    await page.getByRole('dialog').getByRole('button', { name: 'Konfirmasi', exact: true }).click()
    await expect(page.getByText('Diajukan', { exact: true })).toBeVisible()
    await page.goto(path + '/demo-po-03/edit')
    await expect(
        page.getByText('PO tidak dapat diedit pada status atau akses saat ini.'),
    ).toBeVisible()
    await expect(page.getByRole('button', { name: 'Simpan draft' })).toHaveCount(0)
})
test('denies PO menu and direct route without business permissions', async ({ page }) => {
    await login(page, 'unknown@woodflow.test', path)
    await page.goto(path)
    await expect(page).toHaveURL(/forbidden/)
    await expect(page.getByRole('link', { name: 'Purchase Order', exact: true })).toHaveCount(0)
})
